version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
    mongo:
        driver: ${VOLUMES_DRIVER}

services:
    mongo:
        build: ./mongo
        ports:
          - "${MONGODB_PORT}:27017"
        volumes:
          - ${DATA_PATH_HOST}/mongo:/data/db
          - ${DATA_PATH_HOST}/mongo_config:/data/configdb
        networks:
          - backend